### ISSUE TITLE
Module "Weather"

### ISSUE THREAD

**Issue by smostovoy** [molybdenum-99/reality#19]
Module Weather should be included into City and Country entities and it should extend them with weather attributes. Not sure about the gem and service because of the licenses. 
Some options:
https://github.com/coderhs/ruby_open_weather_map
http://openweathermap.org/terms

https://github.com/attack/barometer

**Comment by zverok** [comment]
Barometer seems to have cool API, but uses only proprietary sources :(
OpenWeatherMap's terms are good enough.

**Comment by zverok** [comment]
NB: I made up my mind finally and now I'm totally positive weather should be included in (and only in) `Geo::Coord` type for now.
