### ISSUE TITLE
Extras: time at geographic point

### ISSUE THREAD

**Issue by zverok** [molybdenum-99/reality#21]
**Interface:**

```ruby
# minimal
Reality.city('Buenos-Aires').current_time # => 2016-01-11 06:38:51 -0300

# more:
Reality.city('Buenos-Aires').time(2015, 1, 11, 6, 38) # => 2016-01-11 06:38:00 -0300
Reality.city('Buenos-Aires').time('2015-01-11 06:38')  # => 2016-01-11 06:38:00 -0300

# or, better (?) alternative:
Reality.city('Buenos-Aires').time.zone
Reality.city('Buenos-Aires').time.now
Reality.city('Buenos-Aires').time.local(2015, 1, 11, 6, 38)
Reality.city('Buenos-Aires').time.parse('2015-01-11 06:38')
```

**Implementation:**
* case1: Entity has explicit `time_zone` field: use it;
* case2: Entity has geographic coords, or place name: guess timezone (some [methods](http://stackoverflow.com/questions/16086962/how-to-get-a-time-zone-from-a-location-using-latitude-and-longitude-coordinates) -- maybe [this gem](https://github.com/panthomakos/timezone) should be ok, at least for the beginning)

**Comment by smostovoy** [comment]
should wait for #3 and #17 ?

**Comment by zverok** [comment]
@smostovoy No, I don't think so. 
About #3 (which, in any case, I'll plan to do today/tomorrow) -- there is `Country` already, heaving `time_zone` field.
About #17 -- it seems like earlier (and not well-thought) version of current ticket, let's ignore it for now.

**Comment by zverok** [comment]
NB: some (very rough) city data added.

**Comment by zverok** [comment]
Want something be done, do it yourself :(
https://github.com/zverok/wheretz

**Comment by smostovoy** [comment]
ok, will change to use it)

**Comment by zverok** [comment]
Fixed with `coord.timezone` and `TZOffset` class
