### ISSUE TITLE
Undefined method 'Entity' for main object

### ISSUE THREAD

**Issue by Harrisonl** [molybdenum-99/reality#36]
Trying to have a play around with the gem but keep running into this error. Currently:

```ruby
$ require 'reality'
$ include Reality

$ Entity
$ # => Reality::Entity

$ Entity('Australia')
$ # => Undefined method 'Entity' for main:Object

$ Reality::Entity('Australia')
$ # => #<Reality::Entity(Australia):country>
```

**Comment by apantsiop** [comment]
Happened to me also with MRI Ruby 2.3, reality 0.0.3

**Comment by zverok** [comment]
Sorry, it should be `include Reality::Methods` (which is a bit obscure, faithfully).
Fixed this in README for now, will think of it.
