### ISSUE TITLE
Idea: Default to Wikidata label search if no Wikipedia article found

### ISSUE THREAD

**Issue by Holek** [molybdenum-99/reality#52]
```
> pip = Reality::Entity.new("Piper Club")
=> #<Reality::Entity?(Piper Club)>
> pip.describe
-------------------------------
#<Reality::Entity?(Piper Club)>
-------------------------------
=> nil
```

That's because Piper Club article currently [exists only in Italian Wikipedia](https://it.wikipedia.org/wiki/Piper_Club), but its [Wikidata item](https://www.wikidata.org/wiki/Q3905504) is full of statements that could be imported.

**Comment by zverok** [comment]
https://github.com/molybdenum-99/reality/commit/61bc9ead50d38d87f6468db27069bc015f85fe01 Did it! (Only for singular entities though, not for entity lists. Will fix it later.) 

Also added some useful predicates for your case. In current master it is:

```ruby
pip = Reality::Entity('Piper Club')
# => #<Reality::Entity(Piper Club)> 
pip.describe
# ------------------------------
# #<Reality::Entity(Piper Club)>
# ------------------------------
#             coord: #<Reality::Geo::Coord(41°55′8″N,12°30′4″E)>
#        located_in: #<Reality::Entity?(Rome)>
#  official_website: "http://www.piperclub.it/"
#    street_address: "Via Tagliamento 9"
#  twitter_username: "piperclubroma"
```

**Comment by Holek** [comment]
:clap: Bravo!

**Comment by zverok** [comment]
Added list loading fallback too, now in master. Will came in next release, in 1-2 weeks. So, closing the issue now.
